### ISSUE TITLE
[New instance] https://iv.nboeck.de

### ISSUE THREAD

**Issue by nikobck** [iv-org/documentation#408]
### URL

https://iv.nboeck.de

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Finland

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

```yaml
default_user_preferences:
  quality: dash
  region: DE
  default_home: Trending  # might change in the future
```

Added IPv6 support

Weekly updates, restart every hour
