### ISSUE TITLE
default_user_preferences in the compose file isn't documented anywhere

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/documentation#413]
Multiple people have been reported that they couldn't figure out how to change the default instance settings.

After digging into it... I discovered that it wasn't documented anywhere.

We need to document that this is the expected format:

(this is taken from my own instances)

```
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        check_tables: true
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: postgres
          port: 5432
        https_only: true
        domain: <REDACTED>
        external_port: 443
        log_level: Error
        popular_enabled: false
        registration_enabled: false
        login_enabled: false
        hmac_key: <REDACTED>
        default_user_preferences:
          dark_mode: dark
          feed_menu: []
          default_home: Search
          annotations: true
          annotations_subscribed: true
          related_videos: false
          quality: dash
          quality_dash: 1080p
          local: true
```
