### ISSUE TITLE
config vars incomplete

### ISSUE THREAD

**Issue by jtagcat** [iv-org/documentation#46]
https://github.com/iv-org/invidious/blob/master/src/invidious/helpers/helpers.cr has more

I thought of not porting them manually, and automatically turning the defaults, comments to docs. 2h later I'm going to stop.

Either link to 'find more vars there, but beware the top level keys are wrong and there's bunch of other things as well' or watch the file for changes, and update docs accordingly.

**Comment by jtagcat** [comment]
Here's how far I got.
```
  ConfigPreferences:
    annotations: false
    annotations_subscribed: false
    autoplay: false
    captions: ["", "", ""]
    comments: ["youtube", ""]
    continue: false
    continue_autoplay: true
    dark_mode: ""
    latest_only: false
    listen: false
    local: false
    locale: "en-US"
    max_results: 40
    notifications_only: false
    player_style: "invidious"
    quality: "hd720"
    quality_dash: "auto"
    default_home: "Popular"
    feed_menu: ["Popular", "Trending", "Subscriptions", "Playlists"]
    related_videos: true
    sort: "published"
    speed: 1.0_f32
    thin_mode: false
    unseen_only: false
    video_loop: false
    volume: 100
  Config:
    channel_threads: 1           # Number of threads to use for crawling videos from channels (for updating subscriptions)
    feed_threads: 1              # Number of threads to use for updating feeds
    output: "STDOUT"            # Log file path or STDOUT
    log_level: LogLevel::Info # Default log level, valid YAML values are ints and strings, see src/invidious/helpers/logger.cr
    db: nil                  # Database configuration with separate parameters (username, hostname, etc)
    database_url: URI.parse("")      # Database configuration using 12-Factor "Database URL" syntax
    decrypt_polling: true           # Use polling to keep decryption function up to date
    full_refresh: false             # Used for crawling channels: threads should check all videos uploaded by a channel
    https_only: # Used to tell Invidious it is behind a proxy, so links to resources should be https://
    hmac_key: # HMAC signing key for CSRF tokens and verifying pubsub subscriptions
    domain: # Domain to be used for links to resources on the site where an absolute URL is required
    use_pubsub_feeds: false # Subscribe to channels using PubSubHubbub (requires domain, hmac_key)
    popular_enabled: true
    captcha_enabled: true
    login_enabled: true
    registration_enabled: true
    statistics_enabled: false
    admins: [] of String
    external_port: nil
    default_user_preferences: ConfigPreferences.from_yaml("")
    dmca_content: [] of String    # For compliance with DMCA, disables download widget using list of video IDs
    check_tables: false                    # Check table integrity, automatically try to add any missing columns, create tables, etc.
    cache_annotations: false               # Cache annotations requested from IA, will not cache empty annotations or annotations that only contain cards
    banner: nil                         # Optional banner to be displayed along top of page for announcements, etc.
    hsts: true                            # Enables 'Strict-Transport-Security'. Ensure that `domain` and all subdomains are served securely
    disable_proxy: false # Disable proxying server-wide: options: 'dash', 'livestreams', 'downloads', 'local'
    force_resolve: Socket::Family::UNSPEC # Connect to YouTube over 'ipv6', 'ipv4'. Will sometimes resolve fix issues with rate-limiting (see https://github.com/ytdl-org/youtube-dl/issues/21729)
    port: 3000                                     # Port to listen for connections (overrided by command line argument)
    host_binding: "0.0.0.0"                       # Host to bind (overrided by command line argument)
    pool_size: 100                                 # Pool size for HTTP requests to youtube.com and ytimg.com (each domain has a separate pool of `pool_size`)
    cookies: HTTP::Cookies.new               # Saved cookies in "name1=value1; name2=value2..." format
    captcha_key: nil                               # Key for Anti-Captcha
    captcha_api_url: "https://api.anti-captcha.com" # API URL for Anti-Captcha
  DBConfig:
    user: 
    password: 
    host: 
    port: 
    dbname: 
```
