### ISSUE TITLE
New invidious instance: https://invidious.s1gm4.eu (S1GM4 CHATONS)

### ISSUE THREAD

**Issue by OrnithOrtion** [iv-org/documentation#96]
For S1GM4 CHATONS, we have installed an instance of Invidious.

We have not done any software modification, and if we will, it will be added to our gitea forge: https://forge.s1gm4.eu

You can found this instance here: [https://invidious.s1gm4.eu](https://invidious.s1gm4.eu)

**Comment by syeopite** [comment]
Hi, thanks for hosting a public instance! Before we can add it onto the official list we'll need to know where the instance is hosted at and if it uses any services like Cloudflare.

Also, in preparation for the instance list rewrite (See #74 or #76), could you please enable statistics? 

Thank you!

**Comment by OrnithOrtion** [comment]
I have updated instances.yml, but I do not know how I can send this modified version.

Here is an extract in https section:
```yaml
     - url: https://invidious.s1gm4.eu
       country: FR
       status: 
         url: https://status.s1gm4.eu
       privacy_policy:
       ddos_mitm_protection: null
       owner: https://s1gm4.eu
       is_modified: false
       source: null
```
